### PR TITLE
Support editor to return PromiseLike object

### PR DESCRIPTION
**Pull request by superfreeeee**
Enable editor to return Promise object which contains new JSON object as its value

### CODE REVIEW

**Comment by superfreeeee** [comment]
@rejas hello there, can you please checkout this pull request for me, I really need this feature in my own project

**Comment by rejas** [comment]
@superfreeeee Unfortunately I dont have project anymore where I use this so you have to tell me if is this a breaking change or do have existing projects adjust if I merge this?

**Comment by superfreeeee** [comment]
> @superfreeeee Unfortunately I dont have aproject anymore where I use this. So you have to tell me please: is this a breaking change or do existing projects have to adjust if I merge this?

This will be no breaking change, but enable developers to return PromiseLike object and fit into node Readable stream created by gulp.
After this update, those who use this plugin won't need to change there code, but they can change editor function to async if they need it

**Review by rejas — APPROVED** [review]

**Comment by rejas** [comment]
Thanks for the PR!

**Pull request merged**
